const mapVariablesToColumns = {
    "UDISE CODE": "udise_code",
    "Year": "year", // this is incomplete
    "School Name": "schoolname",
    State: "state",
    District: "district",
    Block: "block",
    "Rural / Urban": "urban",
    Cluster: "cluster",
    Ward: "ward",
    Mohalla: "mohalla",
    Pincode: "pincode",
    Panchayat: "panchayat",
    City: "city",
    Municipality: "municipality",
    "Assembly Const.": "assembly",
    "Parl. Constituency": "parl_const",
    "School Category": "category",
    "School Management": "management",
    "School Type": "type",
    "Lowest & Highest Class": "low_high",
    "Pre Primary": "preprim",
    "Medium 1": "medium1",
    "Medium 2": "medium2",
    "Medium 3": "medium3",
    "Medium 4": "medium4",
    "Year of Establishment": "year_est",
    "Year of Recognition-Pri.": "recog_pri",
    "Year of Recognition-Upr.Pri.": "recog_upr_pri",
    "Year of Recognition-Sec.": "recog_sec",
    "Year of Recognition-Higher Sec.": "recog_highsec",
    "Is this a Shift School?": "shift",
    "Building Status": "building_stat",
    "Boundary Wall": "boundary",
    "No.of Building Blocks": "no_blocks",
    "Pucca Building Blocks": "pucca_blocks",
    "Is Special School for CWSN?": "specialschool",
    "Availability of Ramps": "ramps",
    "Availability of Handrails": "handrails",
    "Anganwadi At Premises": "aganwadi",
    "Anganwadi Boys": "aganwadi_b",
    "Anganwadi Girls": "aganwadi_g",
    "Anganwadi Worker": "aganwadi_worker",
    "Residential School": "residential",
    "Residential Type": "resid_type",
    "Minority School": "minorityschool",
    "Approachable By All Weather Road": "road",
  }

  module.exports = mapVariablesToColumns