const mapVariablesToColumns = {
  "UDISE CODE": "udise_code",
  Year: "year", // this is incomplete
  "School Name": "schoolname",
  State: "state",
  District: "district",
  Block: "block",
  "Rural / Urban": "urban",
  Cluster: "cluster",
  Ward: "ward",
  Mohalla: "mohalla",
  Pincode: "pincode",
  Panchayat: "panchayat",
  City: "city",
  Municipality: "municipality",
  "Assembly Const.": "assembly",
  "Parl. Constituency": "parl_const",
  "School Category": "category",
  "School Management": "management",
  "School Type": "type",
  "Lowest & Highest Class": "low_high",
  "Pre Primary": "preprim",
  "Medium 1": "medium1",
  "Medium 2": "medium2",
  "Medium 3": "medium3",
  "Medium 4": "medium4",
  "Year of Establishment": "year_est",
  "Year of Recognition-Pri.": "recog_pri",
  "Year of Recognition-Upr.Pri.": "recog_upr_pri",
  "Year of Recognition-Sec.": "recog_sec",
  "Year of Recognition-Higher Sec.": "recog_highsec",
  "Is this a Shift School?": "shift",
  "Building Status": "building_stat",
  "Boundary wall": "boundary",
  "No.of Building Blocks": "no_blocks",
  "Pucca Building Blocks": "pucca_blocks",
  "Is Special School for CWSN?": "specialschool",
  "Availability of Ramps": "ramps",
  "Availability of Handrails": "handrails",
  "Anganwadi At Premises": "aganwadi",
  "Anganwadi Boys": "aganwadi_b",
  "Anganwadi Girls": "aganwadi_g",
  "Anganwadi Worker": "aganwadi_worker",
  "Residential School": "residential",
  "Residential Type": "resid_type",
  "Minority School": "minorityschool",
  "Approachable By All Weather Road": "road",
  "Handwash Near Toilet": "handwash",
  "Handwash Facility for Meal": "handwash_meal",
  "Total Class Rooms": "class_tot",
  "In Good Condition": "class_good",
  "Needs Minor Repair": "class_minor",
  "Needs Major Repair": "class_major",
  "Other Rooms": "other_room",
  "Library Availability": "library",
  "Separate Room for HM": "room_hm",
  "Drinking Water Available": "drinking",
  "Drinking Water Functional": "drinking_func",
  "Rain Water Harvesting": "rainwater",
  "Playground Available": "playground",
  "Furniture Availability": "furniture",
  "Electricity Availability": "electric",
  "Solar Panel": "solar",
  "Medical checkups": "medical",
  "ICT Lab": "ict",
  Laptop: "laptop",
  Projector: "projector",
  Internet: "internet",
  Tablet: "tablet",
  DTH: "dth",
  Desktop: "desktop",
  Printer: "printer",
  DigiBoard: "digiboard",
  Total: "tea_total",
  Regular: "tea_reg",
  "Part-time": "tea_part",
  Contract: "tea_contract",
  Male: "tea_male",
  Female: "tea_fem",
  Transgender: "tea_trans",
  "Below Graduate": "qual_below",
  Graduate: "qual_grad",
  "Post Graduate and Above": "tea_post",
  "Diploma or Certificate in basic teachers training": "pqual_dipl", // typos will not pass using this method - see sample doc
  "B.Ed. or Equivalent": "tqual_bed",
  Other: "tqual_other",
  "Diploma/degree in special Education": "tqual_special",
  "Bachelor of Elementary Education (B.El.Ed.)": "tqual_bach",
  "M.Ed. or Equivalent": "tqual_med",
  None: "tqual_none",
  "Pursuing any Relevant Professional Course": "tqual_pursue",
}

module.exports = mapVariablesToColumns
